apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: online-exam
type: Opaque
data:
  # Base64-encoded value of your secret; or set via kubectl create secret
  JWT_SECRET: c3VwZXJfc2VjcmV0X2tleQ==  # echo -n "super_secret_key" | base64